### ISSUE TITLE
🔋❓

### ISSUE THREAD

**Issue by jhersh** [obihann/archey-osx#38]
archey 1.5.2 on my Mac Pro, which sadly lacks a battery, displays `Battery: ?` as part of its output.

I think I preferred archey 1.5.1's take, which omitted the battery line entirely on devices that don't have a battery. I am curious if there's any particular reason for this change? :)

**Comment by obihann** [comment]
@jhersh Thanks for pointing this out. We changed how we poll the battery to speed the startup time, and since I personally don't have a mac without a battery this slipped by me. I'll try to get a fix out for you this week. 

Thanks!

**Comment by childnode** [comment]
yes, confirm, my pr #34 did this, you can easily test this by "mocking" output:
https://github.com/childnode/archey-osx/commit/11c680abd33823716063ef4e40531b53968b13ec#diff-eb0567f739a3de3220b8e9fa66e91e97R79

`echo "fooBar" | awk '$1~/Capacity/{c[$1]=$3} END{OFMT="%.2f%%"; max=c["\"MaxCapacity\""]; print (max>0? 100*c["\"CurrentCapacity\""]/max: "?")}'`
will result in `?` as mentioned by @jhersh 

that's the result blind-copy other guys code from forums without really reading it ;)
`print (max>0? 100*c["\"CurrentCapacity\""]/max: "?")`
better
`if (max>0) { print 100*c["\"CurrentCapacity\""]/max;}`

that's where the ? comes from.

if you @obihann refer to this bug on https://github.com/obihann/archey-osx/commit/78c3df37c43c2007c31d0b5d8a7a1f4cec50258c
=> nope, you will not fix anything with this ;p why do you think formatter change `%.2f%%` to `%.2f%` is causing this or will change anything? you'll just get the next bug, 

fixed in my develop

**Comment by obihann** [comment]
@childnode if you check now I am determining when to show / hide the battery display, we check if the value is empty, but your code would display a % sign with no value when no battery was present. By removing the % until we print then we can properly check if the value was empty and not display it... That being said your pull request looks good as well, so if you can simply resolve the merge conflicts I don't see why we can't get @jhersh to test it out then mark it resolved and release it.

**Comment by childnode** [comment]
hi @obihann 
> if you check now
what? => https://github.com/obihann/archey-osx/commit/78c3df37c43c2007c31d0b5d8a7a1f4cec50258c

and no, the code will **not** display % sign if no value was parsed when no battery was present. 
just tested in an VirtualMachine ...
The [OFMT alias numeric output formatter](https://www.gnu.org/software/gawk/manual/html_node/OFMT.html) just formats what is printed, if nothing is printed if no `MaxCapacity` is found in ioreg, awk must not print `"?"`. That's it!


the "merge conflict" resulted in disregarding your commit https://github.com/obihann/archey-osx/commit/78c3df37c43c2007c31d0b5d8a7a1f4cec50258c.  
ommit your change, that's it

**Comment by jhersh** [comment]
With https://github.com/obihann/archey-osx/commit/78c3df37c43c2007c31d0b5d8a7a1f4cec50258c the output is `Battery: ?%`

**Comment by obihann** [comment]
@childnode @jhersh Sorry for the delay, jumping on this now. I've merged your PR into develop and should have a 1.6 release later this week with it.

**Comment by CamJN** [comment]
Any news on that 1.6 release? I'm a no-battery user as well (actually a laptop with the battery removed) and would appreciate this improvement.

**Comment by obihann** [comment]
I believe we good, latest code via master should contain the fixes.

**Comment by obihann** [comment]
This is now in 1.6.0-pr https://github.com/obihann/archey-osx/releases/tag/1.6.0-pr
